controllers:
    resource: ../src/Controller/
    type: attribute


user_new:
    path: /user/new
    controller: App\Controller\UserController::new
    methods: [GET, POST]

app_first:
    path: /
    controller: App\Controller\FirstController::index


home:
    path: /
    controller: App\Controller\FirstController::index